theme = "mocha"
line-height = 1
confirm-before-quit = false

[cursor]
 shape = 'block'

[editor]
 program = "nvim"
 args = []

[window]
 width = 1280
 height = 720
 mode = "windowed"
 decorations = "Buttonless"


[renderer]
 performance = "high"
 backend = "GL"
 disable-unfocused-render = true
 level = 1

[fonts]
 family = "JetBrainsMono Nerd Font"
 hinting = false
 size = 22

[shell]
 program = "/bin/zsh"
